### ISSUE TITLE
"PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::getOptions() must be an instance of Composer\Script\CommandEvent, instance of Composer\Script\Event given ..."

### ISSUE THREAD

**Issue by gdubicki** [liip/LiipMonitorBundle#147]
Hi,

I am trying to deploy https://github.com/tsteur/open-source-tag-manager . One of the step I have to do is failing with this:

```
gdubicki@host:~/open-source-tag-manager$ composer require liip/monitor-bundle
Using version ^2.5 for liip/monitor-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
Clearing the cache for the dev environment with debug true
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets
Trying to install assets as symbolic links.
Installing assets for Symfony\Bundle\FrameworkBundle into web/bundles/framework
The assets were installed using symbolic links.
Installing assets for Liip\MonitorBundle into web/bundles/liipmonitor
The assets were installed using symbolic links.
Installing assets for Nelmio\ApiDocBundle into web/bundles/nelmioapidoc
The assets were installed using symbolic links.
Installing assets for Sensio\Bundle\DistributionBundle into web/bundles/sensiodistribution
The assets were installed using symbolic links.
Installing assets for SevenTag\Plugin\FacebookRetargetingPixelCustomTemplateBundle into web/bundles/seventagpluginfacebookretargetingpixelcustomtemplate
The assets were installed using symbolic links.
Installing assets for SevenTag\Plugin\CrazyEggCustomTemplateBundle into web/bundles/seventagplugincrazyeggcustomtemplate
The assets were installed using symbolic links.
Installing assets for SevenTag\Plugin\OptimizelyCustomTemplateBundle into web/bundles/seventagpluginoptimizelycustomtemplate
The assets were installed using symbolic links.
Installing assets for SevenTag\Plugin\QualarooCustomTemplateBundle into web/bundles/seventagpluginqualaroocustomtemplate
The assets were installed using symbolic links.
Installing assets for SevenTag\Plugin\VisualWebsiteOptimizerCustomTemplateBundle into web/bundles/seventagpluginvisualwebsiteoptimizercustomtemplate
The assets were installed using symbolic links.
Installing assets for SevenTag\Plugin\GoogleAnalyticsCustomTemplateBundle into web/bundles/seventagplugingoogleanalyticscustomtemplate
The assets were installed using symbolic links.
Installing assets for SevenTag\Plugin\ClickTaleCustomTemplateBundle into web/bundles/seventagpluginclicktalecustomtemplate
The assets were installed using symbolic links.
Installing assets for SevenTag\Plugin\MarketoCustomTemplateBundle into web/bundles/seventagpluginmarketocustomtemplate
The assets were installed using symbolic links.
Installing assets for SevenTag\Plugin\GoogleAdwordsCustomTemplateBundle into web/bundles/seventagplugingoogleadwordscustomtemplate
The assets were installed using symbolic links.
Installing assets for SevenTag\Plugin\SalesManagoCustomTemplateBundle into web/bundles/seventagpluginsalesmanagocustomtemplate
The assets were installed using symbolic links.
Installing assets for SevenTag\Plugin\PiwikCustomTemplateBundle into web/bundles/seventagpluginpiwikcustomtemplate
The assets were installed using symbolic links.
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::removeSymfonyStandardFiles
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget
> Liip\MonitorBundle\Composer\ScriptHandler::checkHealth
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::getOptions() must be an instance of Composer\Script\CommandEvent, instance of Composer\Script\Event given, called in /home/gdubicki/open-source-tag-manager/vendor/liip/monitor-bundle/Composer/ScriptHandler.php on line 16 and defined in /home/gdubicki/open-source-tag-manager/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Composer/ScriptHandler.php:411
Stack trace:
#0 /home/gdubicki/open-source-tag-manager/vendor/liip/monitor-bundle/Composer/ScriptHandler.php(16): Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::getOptions(Object(Composer\Script\Event))
#1 /usr/share/php/Composer/EventDispatcher/EventDispatcher.php(238): Liip\MonitorBundle\Composer\ScriptHandler::checkHealth(Object(Composer\Script\Event))
#2 /usr/share/php/Composer/EventDispatcher/EventDispatcher.php(192): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('Liip\\MonitorBun...', 'checkHealth', Object(Compose in /home/gdubicki/open-source-tag-manager/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Composer/ScriptHandler.php on line 411

Fatal error: Uncaught TypeError: Argument 1 passed to Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::getOptions() must be an instance of Composer\Script\CommandEvent, instance of Composer\Script\Event given, called in /home/gdubicki/open-source-tag-manager/vendor/liip/monitor-bundle/Composer/ScriptHandler.php on line 16 and defined in /home/gdubicki/open-source-tag-manager/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Composer/ScriptHandler.php:411
Stack trace:
#0 /home/gdubicki/open-source-tag-manager/vendor/liip/monitor-bundle/Composer/ScriptHandler.php(16): Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::getOptions(Object(Composer\Script\Event))
#1 /usr/share/php/Composer/EventDispatcher/EventDispatcher.php(238): Liip\MonitorBundle\Composer\ScriptHandler::checkHealth(Object(Composer\Script\Event))
#2 /usr/share/php/Composer/EventDispatcher/EventDispatcher.php(192): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('Liip\\MonitorBun...', 'checkHealth', Object(Compose in /home/gdubicki/open-source-tag-manager/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Composer/ScriptHandler.php on line 411
```

I am using Ubuntu 16.04 here. Please let me know what else do you need to know to help. Thanks!

**Comment by JulienDesurmont** [comment]
You should give a try with an older version of composer.phar
I had quit the same issue and get to it with Composer version 1.5.2
